# Generated by Django 3.1.4 on 2021-01-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('CA', 'Cash'), ('CH', 'Check'), ('WI', 'Wire Transfer')], max_length=2)),
                ('direction', models.CharField(choices=[('IN', 'Deposit'), ('OU', 'Withdraw')], max_length=2)),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount')),
            ],
        ),
    ]
